// <auto-generated />
namespace PMSShopping.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class add_tbl_slide : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_tbl_slide));
        
        string IMigrationMetadata.Id
        {
            get { return "202005120514532_add_tbl_slide"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
